# hugo
baseURL: "https://willrowe.net/recipes"
title: "Will Rowe"
theme: paperModMod
googleAnalytics: UA-90659329-1
enableRobotsTXT: false
buildDrafts: false
buildFuture: true
buildExpired: true
minify:
  disableXML: true
  minifyOutput: true
pagination:
  pagerSize: 11
canonifyURLs: true

# paperMod
outputs:
  home:
    - HTML
    - RSS
    - JSON
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: search
      name: Search
      url: /search/
      weight: 100
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 1000
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 10000

# site content
params:
  env: production
  description: "recipes"
  author: Will
  images: img
  ShowReadingTime: false
  ShowShareButtons: true
  assets:
    favicon: img/angus-duckwalk-compressed.gif
    favicon16x16: img/angus-duckwalk-compressed.gif
    favicon32x32: img/angus-duckwalk-compressed.gif
    apple_touch_icon: img/angus-duckwalk-compressed.gif
    safari_pinned_tab: img/angus-duckwalk-compressed.gif
  label:
    text: "Let There Be Guac"
    iconL: img/angus-duckwalk-compressed.gif
    iconR: img/angus-duckwalk-compressed-flipped.gif
  shoppingLinks:
    "tipo 00 flour": "https://www.amazon.co.uk/gp/product/B0173KM9EY/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1"
    "kombu": "https://www.souschef.co.uk/products/kombu?variant=16897515192378&currency=GBP&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic"
    "gochujang": "https://www.souschef.co.uk/products/gochujang"
    "sriracha": "https://www.souschef.co.uk/products/sriracha-chilli-sauce"
    "lye water (kansui)": "https://www.souschef.co.uk/products/lye-water"
